version: '3.8'

services:
  jenkins-lts:
    image: jenkins/jenkins:lts
    container_name: jenkins-lts
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - "C:/Users/user/PycharmProjects/pytest_framework/aqa_/hw27/jenkins/data:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"